[app]
    name = "orange"
    key = "6ce1c50f7b2f38ee6354f5790cfdccc5"
    debug = true
    httpAddr = "0.0.0.0"
    httpPort = 9088
    maxBody = 2096157
    csrfVerify = false
    maxWaitSecond = 120
    viewPath = "./storage/views"
    prefix ="local"
    [app.logger]
        level = "INFO"
        type = "text"
        path = ""
        syncInterval = 200
[database]
    initCap = 2 #数据库连接池 初始化连接数
    maxCap = 5 #数据库连接池 最大连接数，超过次数后连接则实时生成实时关闭，类似php短链接
    idleTimeout = 5 # 连接空闲释放时间
    debug = true # 是否开启debug，可显示mysql执行的sql语句
    [database.redis]
        [database.redis.default] #redis配置，可以配置多个，默认名称default
            addr = "127.0.0.1:6379"
            password = ""
            dbnum = 7